CREATE TABLE IF NOT EXISTS Sport_club (
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar(100) NOT NULL UNIQUE,
    creation_date date CHECK(extract(year from creation_date) > 1900)
);