CREATE TABLE IF NOT EXISTS Athlete (
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    first_name varchar(100) NOT NULL,
    last_name varchar(100) NOT NULL,
    father_name varchar(100),
    club_id int REFERENCES Sport_club(id) ON DELETE SET NULL
);